sudo: false

language: cpp

compiler:
- gcc
- clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
    - libeigen3-dev

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

before_script:
- cd testing

script:
- ./build_examples.sh

after_success:
- ./run_examples.sh

branches:
  only:
  - master

notifications:
  email:
    recipients:
    - matlabplotter_build@pirmin-schmid.ch
    on_success: always
    on_failure: always

os:
- linux