sudo: false

language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - libeigen3-dev

before_script:
  - cd testing

script:
  - ./build_examples.sh

after_success:
  - ./run_examples.sh

branches:
  only:
    - master

notifications:
  email:
    - "mailbox@pirmin-schmid.ch"

os:
  - linux